framework:
  messenger:
    default_bus: messenger.bus.default
    failure_transport: failed

    transports:
      # Asynchronous transport (e.g. doctrine, AMQP)
      async:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        options:
          use_notify: true
          check_delayed_interval: 60000
        retry_strategy:
          max_retries: 3
          multiplier: 2

      # Failed messages go here
      failed:
        dsn: "doctrine://default?queue_name=failed"

      # Synchronous transport for dev/testing (optional)
      sync: "sync://"

    buses:
      messenger.bus.default: []

    routing:
      # Email messages sent asynchronously
      Symfony\Component\Mailer\Messenger\SendEmailMessage: sync

      # Notifications (chat/sms) also sent async
      Symfony\Component\Notifier\Message\ChatMessage: async
      Symfony\Component\Notifier\Message\SmsMessage: async

      # Add custom messages here
      # App\Message\YourMessage: async
