framework:
    validation:
        enable_annotations: true
        email_validation_mode: html5
        not_compromised_password: false
        mapping:
            paths:
                - '%kernel.project_dir%/src/Entity'

when@test:
    framework:
        validation:
            not_compromised_password: false