controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: [GET, POST]

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register

index:
    path: /home
    controller: App\Controller\HomeController::index
    defaults:
        route: app_home
        permanent: true